/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as MicrophoneRouteImport } from './routes/microphone'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as AssessmentsAssessmentIdRouteImport } from './routes/assessments.$assessmentId'
import { Route as ReportSessionIdRouteImport } from './routes/report.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrophoneRoute = MicrophoneRouteImport.update({
  id: '/microphone',
  path: '/microphone',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsAssessmentIdRoute = AssessmentsAssessmentIdRouteImport.update({
  id: '/$assessmentId',
  path: '/$assessmentId',
  getParentRoute: () => AssessmentsRoute,
} as any)
const ReportSessionIdRoute = ReportSessionIdRouteImport.update({
  id: '/report/$sessionId',
  path: '/report/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/interview': typeof InterviewRoute
  '/microphone': typeof MicrophoneRoute
  '/recruiter': typeof RecruiterRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/interview': typeof InterviewRoute
  '/microphone': typeof MicrophoneRoute
  '/recruiter': typeof RecruiterRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/interview': typeof InterviewRoute
  '/microphone': typeof MicrophoneRoute
  '/recruiter': typeof RecruiterRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/chat'
    | '/interview'
    | '/microphone'
    | '/recruiter'
    | '/assessments/$assessmentId'
    | '/report/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/chat'
    | '/interview'
    | '/microphone'
    | '/recruiter'
    | '/assessments/$assessmentId'
    | '/report/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/chat'
    | '/interview'
    | '/microphone'
    | '/recruiter'
    | '/assessments/$assessmentId'
    | '/report/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  ChatRoute: typeof ChatRoute
  InterviewRoute: typeof InterviewRoute
  MicrophoneRoute: typeof MicrophoneRoute
  RecruiterRoute: typeof RecruiterRoute
  ReportSessionIdRoute: typeof ReportSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microphone': {
      id: '/microphone'
      path: '/microphone'
      fullPath: '/microphone'
      preLoaderRoute: typeof MicrophoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/report/$sessionId': {
      id: '/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof ReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsAssessmentIdRoute: typeof AssessmentsAssessmentIdRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsAssessmentIdRoute: AssessmentsAssessmentIdRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  ChatRoute: ChatRoute,
  InterviewRoute: InterviewRoute,
  MicrophoneRoute: MicrophoneRoute,
  RecruiterRoute: RecruiterRoute,
  ReportSessionIdRoute: ReportSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
